Repository streamshub/console, pull requests merged in 2024-10, with the labels that each got.

#1082 Bump quarkus.platform.version from 3.8.6 to 3.15.1
  .github/workflows/playwright-tests.yml
  pom.xml
  ui/.gitignore
Labels: dependencies, java

#1096 Backport 0.3.6
  ui/package-lock.json
  ui/package.json
Labels: dependencies, javascript

#1121 Obtain topic/partition overview counts from topics API, not metrics
  api/src/main/java/com/github/streamshub/console/api/model/Topic.java
  api/src/main/java/com/github/streamshub/console/api/service/TopicService.java
  ui/api/kafka/actions.ts
  ui/api/kafka/kpi.promql.ts
  ui/api/kafka/schema.ts
  ui/api/topics/actions.ts
  ui/api/topics/schema.ts
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/topics/[topicId]/TopicHeader.tsx
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/overview/ConnectedTopicsPartitionsCard.tsx
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/overview/page.tsx
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/messages/page.tsx
  ui/components/ClusterOverview/TopicsPartitionsCard.tsx
  ui/components/TopicsTable/TopicsTable.tsx
  ui/messages/en.json
Labels: ui

#1111 feat: pause reconciliation
  ui/api/kafka/actions.ts
  ui/api/kafka/schema.ts
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/overview/ConnectButton.tsx
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/overview/page.tsx
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/layout.tsx
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/overview/ConnectedClusterCard.tsx
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/overview/page.tsx
  ui/app/[locale]/(authorized)/layout.tsx
  ui/components/AppLayout.tsx
  ui/components/ClusterOverview/ClusterCard.stories.tsx
  ui/components/ClusterOverview/ClusterCard.tsx
  ui/components/ClusterOverview/PageLayout.stories.tsx
  ui/components/ClusterOverview/ReconciliationModal.tsx
  ui/components/ReconciliationContext.tsx
  ui/components/ReconciliationPausedBanner.tsx
  ui/components/ReconciliationProvider.tsx
  ui/messages/en.json
Labels: ui
