Repository streamshub/console, pull requests merged in 2025-07, with the labels that each got.

#1743 Get kafka version from spec when Reconciliation is paused
  api/src/main/java/com/github/streamshub/console/api/service/KafkaClusterService.java
  api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceIT.java
Labels: java, api

#1752 fix: allow duplicate Kafka cluster names in different namespaces
  api/src/main/java/com/github/streamshub/console/api/support/KafkaContext.java
  api/src/test/java/com/github/streamshub/console/kafka/systemtest/TestPlainProfile.java
  common/src/main/java/com/github/streamshub/console/config/KafkaClusterConfig.java
  common/src/main/java/com/github/streamshub/console/config/KafkaConfig.java
  common/src/test/java/com/github/streamshub/console/config/ConsoleConfigTest.java
Labels: backport/0.6.x, backport/0.8.x

#1776 [ST] Manage and update several dependencies to override Quarkus versions
  systemtests/pom.xml
Labels: dependencies

#1780 fix: include namespace in cluster-scoped names, refine CR conditions
  operator/src/main/java/com/github/streamshub/console/ConsoleReconciler.java
  operator/src/main/java/com/github/streamshub/console/api/v1alpha1/status/ConsoleStatus.java
  operator/src/main/java/com/github/streamshub/console/dependents/BaseClusterRole.java
  operator/src/main/java/com/github/streamshub/console/dependents/BaseClusterRoleBinding.java
  operator/src/main/java/com/github/streamshub/console/dependents/ConfigurationProcessor.java
  operator/src/test/java/com/github/streamshub/console/ConsoleReconcilerTest.java
  operator/src/test/java/com/github/streamshub/console/ConsoleReconcilerTestBase.java
Labels: backport/0.8.x

#1785 fix: manage dependencies for vulnerabilities
  pom.xml
Labels: backport/0.8.x
