Repository streamshub/console, pull requests merged in 2025-01, with the labels that each got.

#1341 Bump several dependencies: Next.js and postcss (0.3.x)
  install/resources/kafka/console-kafka.kafka.yaml
  ui/package-lock.json
  ui/package.json
Labels: dependencies, ui

#1350 Use dependabot for test image updates, rm obsolete/cleanup test code
  .github/dependabot.yml
  api/pom.xml
  api/src/test/java/com/github/streamshub/console/kafka/systemtest/TestOAuthProfile.java
  api/src/test/java/com/github/streamshub/console/kafka/systemtest/TestPlainNoK8sProfile.java
  api/src/test/java/com/github/streamshub/console/kafka/systemtest/TestPlainProfile.java
  api/src/test/java/com/github/streamshub/console/kafka/systemtest/deployment/DeploymentManager.java
  api/src/test/java/com/github/streamshub/console/kafka/systemtest/deployment/KafkaContainer.java
  api/src/test/java/com/github/streamshub/console/kafka/systemtest/deployment/KafkaOAuthSecuredResourceManager.java
  api/src/test/java/com/github/streamshub/console/kafka/systemtest/deployment/KafkaResourceManager.java
  api/src/test/java/com/github/streamshub/console/kafka/systemtest/deployment/KafkaUnsecuredResourceManager.java
  api/src/test/java/com/github/streamshub/console/kafka/systemtest/deployment/KeycloakResourceManager.java
  api/src/test/java/com/github/streamshub/console/kafka/systemtest/deployment/KeycloakSecuredKafkaContainer.java
  api/src/test/resources/Dockerfile.kafka
  api/src/test/resources/Dockerfile.keycloak
  api/src/test/resources/kafka-oauth/config/log4j.properties
  api/src/test/resources/kafka-oauth/env.properties
  api/src/test/resources/kafka-oauth/scripts/functions.sh
  api/src/test/resources/kafka-oauth/scripts/simple_kafka_config.sh
  api/src/test/resources/kafka-oauth/scripts/start.sh
  api/src/test/resources/keycloak/authz-realm.json
Labels: java, api, docker

#1245 Provide a way to override operand image, env, and resources in CRD
  operator/src/main/java/com/github/streamshub/console/api/v1alpha1/spec/ConsoleSpec.java
  operator/src/main/java/com/github/streamshub/console/api/v1alpha1/spec/containers/ContainerSpec.java
  operator/src/main/java/com/github/streamshub/console/api/v1alpha1/spec/containers/ContainerTemplateSpec.java
  operator/src/main/java/com/github/streamshub/console/api/v1alpha1/spec/containers/Containers.java
  operator/src/main/java/com/github/streamshub/console/dependents/ConsoleDeployment.java
  operator/src/test/java/com/github/streamshub/console/ConsoleReconcilerTest.java
  operator/src/test/java/com/github/streamshub/console/ConsoleReconcilerTestBase.java
Labels: java, ready for review

#1374 Move Reconciliation pause button to kafka details card
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/overview/ConnectButton.tsx
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/@header/overview/page.tsx
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/overview/ConnectedClusterCard.tsx
  ui/components/ClusterOverview/ClusterCard.stories.tsx
  ui/components/ClusterOverview/ClusterCard.tsx
  ui/components/ClusterOverview/ReconciliationPauseButton.tsx
  ui/components/ClusterOverview/components/ErrorsAndWarnings.tsx
  ui/messages/en.json
Labels: ui

#1377 build(deps): bump org.apache.kafka:kafka-clients from 3.7.1 to 3.9.0
  pom.xml
Labels: dependencies, java

#1393 Move schema link to message details drawer
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/messages/ConnectedMessagesTable.tsx
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/messages/page.tsx
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/topics/[topicId]/messages/schema/ConnectedSchema.tsx
  ui/app/[locale]/(public)/schema/ConnectedSchema.tsx
  ui/app/[locale]/(public)/schema/page.tsx
  ui/components/MessagesTable/MessagesTable.tsx
  ui/components/MessagesTable/components/MessageDetails.tsx
  ui/middleware.ts
Labels: enhancement, ui
