Repository streamshub/console, pull requests merged in 2025-05, with the labels that each got.

#1664 Add support for filtering Kafka clusters by name
  api/src/main/java/com/github/streamshub/console/api/KafkaClustersResource.java
  api/src/main/java/com/github/streamshub/console/api/model/KafkaClusterFilterParams.java
  api/src/main/java/com/github/streamshub/console/api/service/KafkaClusterService.java
  api/src/test/java/com/github/streamshub/console/api/KafkaClustersResourceIT.java
  ui/api/kafka/actions.ts
  ui/app/[locale]/(public)/(home)/ConnectedClustersTable.tsx
  ui/app/[locale]/(public)/(home)/page.tsx
  ui/components/ClustersTable.tsx
Labels: api, ui

#1671 docs(console): updates for kraft support
  docs/sources/modules/con-brokers-page.adoc
  docs/sources/modules/con-consumer-groups-page.adoc
  docs/sources/modules/con-navigating-the-console.adoc
  docs/sources/modules/con-topics-page.adoc
  docs/sources/modules/proc-accessing-connection-details.adoc
  docs/sources/modules/proc-changing-topic-configuration.adoc
  docs/sources/modules/proc-checking-consumer-groups-members.adoc
  docs/sources/modules/proc-checking-topic-configuration.adoc
  docs/sources/modules/proc-checking-topic-consumer-groups.adoc
  docs/sources/modules/proc-checking-topic-messages.adoc
  docs/sources/modules/proc-checking-topic-partitions.adoc
  docs/sources/modules/proc-creating-topics.adoc
  docs/sources/modules/proc-deleting-topics.adoc
  docs/sources/modules/proc-logging-in.adoc
  docs/sources/modules/proc-managing-rebalances.adoc
  docs/sources/modules/proc-pausing-reconciliation.adoc
  docs/sources/modules/proc-resetting-consumer-offsets.adoc
Labels: documentation

#1689 docs(overview): updates the cluster overview page for new filter
  docs/sources/modules/proc-logging-in.adoc
Labels: doc

#1694 fix truncated values
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/consumer-groups/ConsumerGroupsTable.tsx
  ui/components/Table/Toolbar/ChipFilter/components/FilterSwitcher.tsx
Labels: ui

#1696 fix: choose node icon based on aggregate status
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/DistributionChart.stories.tsx
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/DistributionChart.tsx
  ui/app/[locale]/(authorized)/kafka/[kafkaId]/nodes/page.tsx
  ui/utils/config.ts
Labels: ready for review
